[package]
name = "vue-rust-example-canvas"
version = "0.1.0"
authors = ["Gerard Muñoz <gmunoz1979@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/libs/lib.rs"

[dependencies]
wasm-bindgen = "0.2.51"
lazy_static = "1.4.0"
rand = { version = "0.7.2", features = ["wasm-bindgen"] }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
]